name: Build & Publish org-structure-api image

on:
  push:
    branches: [ dev, main ]
    paths:
      - "app/**"
      - ".deployment/**"
      - "pyproject.toml"
      - "uv.lock"
      - ".github/actions/**"
      - ".github/workflows/build.yml"
  workflow_dispatch: {}

jobs:
  build-org-structure-api:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Prepare image tags
        id: meta
        shell: bash
        run: |
          if [[ "${GITHUB_REF_NAME}" == "main" ]]; then
            BRANCH_BASED_TAG="stable"
          else
            BRANCH_BASED_TAG="latest"
          fi
          echo "BRANCH_BASED_TAG=${BRANCH_BASED_TAG}" >> "$GITHUB_OUTPUT"

          IMAGE_DATE_TAG="$(date -u +'%Y.%m.%d')"
          echo "IMAGE_DATE_TAG=${IMAGE_DATE_TAG}" >> "$GITHUB_OUTPUT"

          IMAGE_TAG="${IMAGE_DATE_TAG}-${BRANCH_BASED_TAG}"
          echo "IMAGE_TAG=${IMAGE_TAG}" >> "$GITHUB_OUTPUT"

          echo "COMMIT_TAG=${GITHUB_SHA::7}" >> "$GITHUB_OUTPUT"

      - name: Build & push org-structure-api image
        uses: ./.github/actions/build
        with:
          image: ghcr.io/ilia2003/org-structure-api
          branch-based-tag: ${{ steps.meta.outputs.BRANCH_BASED_TAG }}
          image-date-tag: ${{ steps.meta.outputs.IMAGE_DATE_TAG }}
          image-tag: ${{ steps.meta.outputs.IMAGE_TAG }}
          commit-tag: ${{ steps.meta.outputs.COMMIT_TAG }}
          context: .
          dockerfile: .deployment/Dockerfile
          build-args: ""
          registry-password: ${{ secrets.GITHUB_TOKEN }}
